# Generated by Django 2.2.5 on 2019-09-17 03:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='Image',
            new_name='image',
        ),
    ]
