# Generated by Django 2.2.5 on 2020-06-17 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_interests'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='summary',
        ),
        migrations.AddField(
            model_name='job',
            name='body',
            field=models.CharField(default='body default', max_length=1000),
        ),
        migrations.AddField(
            model_name='job',
            name='title',
            field=models.CharField(default='title default', max_length=100),
        ),
    ]
