# Generated by Django 2.2.5 on 2020-06-17 13:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0005_auto_20200617_1427'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
