# Generated by Django 2.2.5 on 2020-06-18 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0006_job_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='job_type',
            field=models.CharField(choices=[('H', 'Hardware'), ('S', 'Software')], default='S', max_length=1),
        ),
    ]
