# Generated by Django 2.2.5 on 2020-06-18 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0007_job_job_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interests',
            name='summary',
            field=models.TextField(default='title default'),
        ),
        migrations.AlterField(
            model_name='job',
            name='body',
            field=models.TextField(default='body default'),
        ),
    ]
