# Generated by Django 2.2.5 on 2019-09-17 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_blog_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='pubDate',
            field=models.DateField(auto_now=True),
        ),
    ]
