# Generated by Django 2.2.5 on 2019-09-17 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_blog_pubdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='footer',
            field=models.CharField(default=None, max_length=200),
        ),
    ]
