# Generated by Django 2.2.5 on 2019-09-17 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20190916_2115'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='footer',
        ),
        migrations.AlterField(
            model_name='blog',
            name='body',
            field=models.TextField(),
        ),
    ]
