# Generated by Django 2.2.5 on 2020-06-17 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20190916_2230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='image',
            field=models.ImageField(default='../portfolio/static/mohammed.jpg', upload_to='images/'),
        ),
    ]
