# Generated by Django 2.2.5 on 2020-07-11 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='comment_data',
            new_name='body',
        ),
    ]
